main:
  - identifier: "post"
    name: "文章"
    url: "/posts/"
    weight: 1
  - identifier: "tags"
    name: "标签"
    url: "/tags/"
    weight: 2
  - identifier: "categories"
    name: "分类"
    url: "/categories/"
    weight: 3
  - identifier: "profile"
    name: "关于"
    url: "/authors/stephen"
    weight: 4
  - identifier: "seperator"
    pre: <span class='menu-item delimiter'></span>
    weight: 5
  - identifier: "travellings"
    # name: 开往
    pre: "<img src='https://www.travellings.cn/assets/logo.gif' alt='' style='display:inline-block; margin:auto;' width='120'/>"
    url: "https://www.travellings.cn/go.html"
    weight: 100
